[project]
name = "first-task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.10.0",
    "huggingface-hub>=0.34.4",
    "llama-cpp-python>=0.3.15",
]
